{
 "title": "VentiPanstamp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Lüfter Steuerung",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lüfter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"venti\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"stockaufbau\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with Stockaufbau: if (uint(v: r._value) * uint(v: 3600000000000)) -(uint(v: now()) - uint(v: r._time))  >=0  and (uint(v: r._value) * uint(v: 3600000000000)) -(uint(v: now()) - uint(v: r._time))  <= 1844674388946713400 then (uint(v: r._value) * uint(v: 3600000000000)) -(uint(v: now()) - uint(v: r._time))  else uint(v: 0)}))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_RO1_status\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"OFF\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with ON: if uint(v: now()) - uint(v: r._time) >= uint(v: 600000000000) then uint(v: now()) - uint(v: r._time) else uint(v: 0)}))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_RO1_status\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"ON\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with OFF: if uint(v: now()) - uint(v: r._time) >= uint(v: 600000000000) then uint(v: now()) - uint(v: r._time) else uint(v: 0)}))\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Außen Temperatur / Luftfeuchte / Trockenmasse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"outdoor00\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_temperature\" or r[\"_measurement\"] == \"device_frmpayload_data_humidity\" or r[\"_measurement\"] == \"device_frmpayload_data_trockenmasse\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lüfter Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_RO1_status\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Sonden Temperatur / Luftfeuchte / Trockenmasse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] != \"outdoor00\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_temperature\" or r[\"_measurement\"] == \"device_frmpayload_data_humidity\" or r[\"_measurement\"] == \"device_frmpayload_data_trockenmasse\")\r\n  |> filter(fn: (r) => r._value <= 150 and r._value >= -150)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Betriebsstunden",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: -31d)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_RO1_status\")\r\n  |> elapsed(unit: 1s)\r\n  |> map(fn: (r) => ({ r with elapsedFloat: float(v: r.elapsed)/3600.0 }))\r\n  |> filter(fn: (r) => r[\"_value\"] == \"ON\")\r\n  |> aggregateWindow(every: 1d, fn: sum, column:\"elapsedFloat\")\r\n  |> yield(name: \"sum\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_battery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Empfang RSSI",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_rssi\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System Befehle",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  { "title": "Control Parameter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Regel Parameter",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Outdoor Values",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jokley_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"outdoor00\")\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"device_frmpayload_data_temperature\" or r[\"_measurement\"] == \"device_frmpayload_data_humidity\"  or r[\"_measurement\"] == \"device_frmpayload_data_trockenmasse\" or r[\"_measurement\"] == \"device_frmpayload_data_sdef\" )\r\n  |> filter(fn: (r) => r._value <= 100 and r._value >= -100)\r\n  |> last()\r\n\r\n  \r\n    \r\n"
    }
   ]
  },
  {
   "title": "Probe min  Values",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "                from(bucket: \"jokley_bucket\")\r\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n                |> filter(fn: (r) => r[\"device_name\"] == \"probe01\" or r[\"device_name\"] == \"probe02\")\r\n                |> filter(fn: (r) =>  r[\"_measurement\"] == \"device_frmpayload_data_temperature\" or r[\"_measurement\"] == \"device_frmpayload_data_humidity\"  or r[\"_measurement\"] == \"device_frmpayload_data_trockenmasse\" or r[\"_measurement\"] == \"device_frmpayload_data_sdef\" )\r\n                |> filter(fn: (r) => r._value <= 100 and r._value >= -100)\r\n                |> last()\r\n                |> group(columns: [\"_measurement\"])\r\n                |> min()"
    }
   ]
  },
  {
   "title": "Probe max Values",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "                from(bucket: \"jokley_bucket\")\r\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n                |> filter(fn: (r) => r[\"device_name\"] == \"probe01\" or r[\"device_name\"] == \"probe02\")\r\n                |> filter(fn: (r) =>  r[\"_measurement\"] == \"device_frmpayload_data_temperature\" or r[\"_measurement\"] == \"device_frmpayload_data_humidity\"  or r[\"_measurement\"] == \"device_frmpayload_data_trockenmasse\" or r[\"_measurement\"] == \"device_frmpayload_data_sdef\" )\r\n                |> filter(fn: (r) => r._value <= 100 and r._value >= -100)\r\n                |> last()\r\n                |> group(columns: [\"_measurement\"])\r\n                |> max()"
    }
   ]
  }
 ]
}